const productSchema = {
  name: "product",
  title: "Product",
  type: "document",
  fields: [
    {
      name: "name",
      title: "Product Name",
      type: "string",
      validation: (Rule) => Rule.required(),
      readOnly: false,
    },
    {
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
        source: "name",
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
      readOnly: false,
    },
    {
      name: "image",
      title: "Product Image",
      type: "image",
      options: {
        hotspot: true,
      },
      validation: (Rule) => Rule.required(),
      readOnly: false,
    },
    {
      name: "images",
      title: "Additional Images",
      type: "array",
      of: [{ type: "image" }],
      readOnly: false,
    },
    {
      name: "category",
      title: "Category",
      type: "reference",
      to: [{ type: "category" }],
      validation: (Rule) => Rule.required(),
      readOnly: false,
    },
    {
      name: "price",
      title: "Price",
      type: "number",
      validation: (Rule) => Rule.required().min(0),
      readOnly: false,
    },
    {
      name: "originalPrice",
      title: "Original Price",
      type: "number",
      validation: (Rule) => Rule.min(0),
      readOnly: false,
    },
    {
      name: "description",
      title: "Description",
      type: "text",
      rows: 4,
      validation: (Rule) => Rule.required(),
      readOnly: false,
    },
    {
      name: "longDescription",
      title: "Long Description",
      type: "array",
      of: [{ type: "block" }],
      readOnly: false,
    },
    {
      name: "benefits",
      title: "Benefits",
      type: "array",
      of: [{ type: "string" }],
      readOnly: false,
    },
    {
      name: "ingredients",
      title: "Ingredients",
      type: "array",
      of: [{ type: "string" }],
      readOnly: false,
    },
    {
      name: "usage",
      title: "How to Use",
      type: "text",
      rows: 3,
      readOnly: false,
    },
    {
      name: "stockQuantity",
      title: "Stock Quantity",
      type: "number",
      validation: (Rule) => Rule.required().min(0),
      readOnly: false,
    },
    {
      name: "sku",
      title: "SKU",
      type: "string",
      readOnly: false,
    },
    {
      name: "weight",
      title: "Weight (in grams)",
      type: "number",
      readOnly: false,
    },
    {
      name: "isFeatured",
      title: "Featured Product",
      type: "boolean",
      initialValue: false,
      readOnly: false,
    },
    {
      name: "isNewArrival",
      title: "New Arrival",
      type: "boolean",
      initialValue: false,
      readOnly: false,
    },
    {
      name: "rating",
      title: "Average Rating",
      type: "number",
      validation: (Rule) => Rule.min(0).max(5),
      readOnly: false,
    },
  ],
  preview: {
    select: {
      title: "name",
      media: "image",
      subtitle: "category.name",
    },
  },
};

export default productSchema;